dist: trusty
sudo: required

language: go
cache:
  directories:
  - $HOME/.cache/pip
  - $HOME/.cache/pre-commit

go:
  - 1.13.x

addons:
  apt:
    packages:
      - python
      - python-dev
      - python-pip

branches:
  only:
  - gh-pages
  - develop
  - "/release-*/"
  - "/^v\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"

stages:
  - linting

jobs:
  include:
    - stage: linting

      name: "pre-commit"

      before_install:

      install:
        - sudo pip install --upgrade pip
        - sudo pip install yapf==v0.29.0
        - sudo pip install pre-commit
        - go get -u golang.org/x/lint/golint

      script: pre-commit run --all --show-diff-on-failure

      after_success:
        - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
 
 notifications:
   webhooks:
     urls:
       - https://webhooks.gitter.im/e/c917f392fcc5a7120514
     on_success: change  # options: [always|never|change] default: always
     on_failure: always  # options: [always|never|change] default: always
     on_start: never     # options: [always|never|change] default: always

